#! /bin/sh

bspc config top_padding 0
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore

compton -r 12 -o 0.60 -l -10 -t -10 -I 0.01 -O 0.01 -G -D 1 -f -b
~/.config/bspwm/lemonbar/bar.sh
